# General
ZSH_THEME="robbyrussell"
# CASE_SENSITIVE="true"
HYPHEN_INSENSITIVE="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
zstyle ':omz:update' frequency 30 # Update frequency
typeset -U path # Only allow unique entries in the PATH variable

# Export
export LANG=en_US.UTF-8
export PATH=~/.local/bin:$PATH
export ZSH="$HOME/.oh-my-zsh"
export EDITOR="nvim"
# Fuzzystuff (fzf)
export FZF_DEFAULT_OPTS="--height=40% --layout=reverse-list --info=inline --margin=1 --padding=1"
export FZF_DEFAULT_COMMAND='fdfind --type f --strip-cwd-prefix --hidden --follow --exclude .git'
export FZF_TMUX=1
#export FZF_TMUX_OPTS="-p 80%,60%"
export FZF_TMUX_OPTS="-d"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

[ -f $ZSH/oh-my-zsh.sh ] && source $ZSH/oh-my-zsh.sh

# Plugins
plugins=(git ripgrep fzf fzf-tab)

# Preferred editor for local and remote sessions
 if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
 else
   export EDITOR='nvim'
 fi

# Setup fzf
# ---------
if [[ ! "$PATH" == */home/kwogga/.fzf/bin* ]]; then
  PATH="${PATH:+${PATH}:}/home/kwogga/.fzf/bin"
fi

# Auto-completion
# ---------------
source "/home/kwogga/.fzf/shell/completion.zsh"

# Key bindings
# ------------
source "/home/kwogga/.fzf/shell/key-bindings.zsh"

[ -f $HOME/.dotfiles/zsh/zprofile ] && source $HOME/.dotfiles/zsh/zprofile
[ -f $HOME/.zshenv-local ] && source $HOME/.zshenv-local
